### ISSUE TITLE
Could not cast value of type 'UIViewController' to 'WWCalendarTimeSelector.WWCalendarTimeSelector' 

### ISSUE THREAD

**Issue by rahulmehndiratta** [weilsonwonder/WWCalendarTimeSelector#79]
Could not cast value of type 'UIViewController' to 'WWCalendarTimeSelector.WWCalendarTimeSelector'

**Comment by leninsmannath** [comment]
Issue fixed by specifying module "WWCalendarTimeSelector" on "ClockView" and Viewcontroller

![screen shot 2018-07-04 at 10 18 05 am](https://user-images.githubusercontent.com/20436542/42257452-3191b086-7f74-11e8-91d7-171a9f1eb005.png)

![screen shot 2018-07-04 at 10 18 24 am](https://user-images.githubusercontent.com/20436542/42257458-35e18bb6-7f74-11e8-9d5c-75f18624e9e4.png)

**Comment by IOSDeveloperProgrammer** [comment]
@leninsmannath  still i did not solve the issue ? i am getting same error. i was followed your steps
